### ISSUE TITLE
Travis key

### ISSUE THREAD

**Issue by Alexsey** [davidbanham/express-async-errors#10]
Isn't it's the private key in the repo?

**Comment by davidbanham** [comment]
Hi @Alexsey, sorry it's taken me a while to get back to you.

Are you referrign to this line:

https://github.com/davidbanham/express-async-errors/blob/master/.travis.yml#L10

? If so, no. That's an encrypted string. You can read more about it here:

https://docs.travis-ci.com/user/encryption-keys/
