### ISSUE TITLE
A unexpected behavior after just reading README.md

### ISSUE THREAD

**Issue by JaosnHsieh** [davidbanham/express-async-errors#26]
For those who didn't catch error correctly.

`index.js`

```javascript
const express = require('express');
require('express-async-errors');
const router = express.Router();
const app = express();
router.get('/1', async (req, res)=>{
  throw new Error('1 error);
});
app.use('/test', router);
app.use((err, req, res, next)=>{
  console.log('got error', err.message);
});
```
above code works well when `new Express.Router()` and `require('express-async-errors')` in the same file. but below code will not catch error when it's in different file and in the `router.js` file has no `require('express-async-errors')`

below code will not catch error

`index.js`

```javascript
const express = require('express');
const app = express();
const router = require('./router.js');
require('express-async-errors');
app.use('/test', router);
app.use((err, req, res, next)=>{
  console.log('got error', err.message);
});
```

`router.js`

```javascript
const express =require('express');
const router = express.Router();
router.get('/1', async (req, res)=>{
  throw new Error('1 error);
});
module.exports = router;
```

add `require('express-async-errors');` in `router.js` can fix it.

**Comment by luckstar77** [comment]
> For those who didn't catch error correctly.
> 
> `index.js`
> 
> ```js
> const express = require('express');
> require('express-async-errors');
> const app = express();
> const router = express.Router();
> router.get('/1', async (req, res)=>{
>   throw new Error('1 error);
> });
> app.use('/test', router);
> app.use((err, req, res, next)=>{
>   console.log('got error', err.message);
> });
> ```
> 
> above code works well when `new Express.Router()` and `require('express-async-errors')` in the same file. but below code will not catch error when it's in different file and in the `router.js` file has no `require('express-async-errors')`
> 
> below code will not catch error
> 
> `index.js`
> 
> ```js
> const express = require('express');
> const app = express();
> require('express-async-errors');
> const router = require('./router.js');
> app.use('/test', router);
> app.use((err, req, res, next)=>{
>   console.log('got error', err.message);
> });
> ```
> 
> `router.js`
> 
> ```js
> const express =require('express');
> const router = express.Router();
> router.get('/1', async (req, res)=>{
>   throw new Error('1 error);
> });
> module.exports = router;
> ```
> 
> add `require('express-async-errors');` in `router.js` can fix it.

I also faced this situation, the above helped a lot for me.

**Comment by JaosnHsieh** [comment]
I have just realized that if `require('express-async-errors');` above `const router = require('./router.js');`  will solve the problem as well, since `express-async-errors` is some script to modify `express` router's code.

**Comment by davidbanham** [comment]
It's subtle behaviour if you're not familiar with how this aspect of nodejs' modules system works or the patching mechanism used by this library and others like it. I think the README does a good enough job of laying out the requirements for this to work given an assumed understanding of the underlying frameworks. If anyone can think of a clearer way to explain things in the README though I'm happy to take PRs!
