### ISSUE TITLE
Async error handling not working with typescript 

### ISSUE THREAD

**Issue by leonardootoni** [davidbanham/express-async-errors#27]
Hi. I am using express-async-errors 3.1.1 in a express + typescript project.
For some reason, the lib is not catching up async errors from my middlewares.
I followed the instructions, including the error middleware just after all the Application Routes registration.

There is any problem using this with typescript and ts-node?
I also tried to use require() instead of import, without any success.

Down below I put my bootstrap class just to demonstrate the initial setup.
I would welcome any suggestions.
Tks!

```
import 'dotenv/config';
import express, { Request, Response, NextFunction } from 'express';
import 'express-async-errors';
// general imports...
```

```
class Application {
  private instance: express.Application;

  public constructor() {
    this.instance = express();
  }

  public async startupApp(port: number): Promise<this | undefined> {
   
       ...

      // General error handler
      this.instance.use((err: Error, req: Request, res: Response, next: NextFunction) => {
        logger.error('Internal Error: ', err);
        return res.status(500).json({ message: 'Internal Server error.' });
      });

     ...
  }
}
```

**Comment by leonardootoni** [comment]
It is not a lib problem. Also, It is working fine with typescript.
My problem was a silly non-return from an arrow function on my route declaration...

**Comment by ypicard** [comment]
My router declarations were in separate files. I had to import this lib in each of them:
```
import { Router } from 'express';
import 'express-async-errors';
```
