### ISSUE TITLE
Keep Reference on originalHandle

### ISSUE THREAD

**Issue by Uzlopak** [davidbanham/express-async-errors#31]
I needed to keep the original handle, so I extended your code in my fork like this:

```
	Object.defineProperty(newFn, 'originalHandle', {
		value: fn,
		writable: false,
	});
```

**Comment by davidbanham** [comment]
Cool, thanks for getting in touch. Is this something you're proposing as an additional feature or just an FYI?

**Comment by Uzlopak** [comment]
I didnt know if you think it is useful for you or not. If you think this is useful, I would say, that you should add it :).
