### ISSUE TITLE
Avoid logging catched errors

### ISSUE THREAD

**Issue by ManuLpz4** [davidbanham/express-async-errors#44]
Hey, guys! How is it going? Do you know any way to avoid logging all the catched errors? It's a bit dirty in my honest opinion :(
<img width="1057" alt="Captura de Pantalla 2022-12-30 a la(s) 22 47 32" src="https://user-images.githubusercontent.com/17878459/210121458-0b670cac-bf24-4b1d-9912-4856dade2944.png">

**Comment by damir-bajramovic** [comment]
@ManuLpz4  Are you sure you're not explicitly logging the error in your middleware? I don't get those logs unless I explicitly call `console.error` from my middleware. 

Another caveat is, your global exception-handling middleware should be the last middleware in your middleware chain. Could you try something like shown in the image?
![image](https://user-images.githubusercontent.com/30154316/212771445-19ddf278-6f94-4384-b931-e7bb2763b0bc.png)

**Comment by ManuLpz4** [comment]
> @ManuLpz4  Are you sure you're not explicitly logging the error in your middleware? I don't get those logs unless I explicitly call `console.error` from my middleware. 
> 
> 
> 
> Another caveat is, your global exception-handling middleware should be the last middleware in your middleware chain. Could you try something like shown in the image?
> 
> ![image](https://user-images.githubusercontent.com/30154316/212771445-19ddf278-6f94-4384-b931-e7bb2763b0bc.png)
> 
> 

I come to my house, try it and answer. Thank you for taking the time to helping me

**Comment by damir-bajramovic** [comment]
@ManuLpz4 You're welcome! Please, do tell if it works. I had the issue myself.

**Comment by ManuLpz4** [comment]
> @ManuLpz4 You're welcome! Please, do tell if it works. I had the issue myself.

With the approach below every error is logged in the console even if I use a error handler :(

![image](https://user-images.githubusercontent.com/17878459/212795514-4d085c41-7a70-45ef-8467-ccb4cecb1433.png)

**Comment by ManuLpz4** [comment]
Fixed! Thank you so much Dam for helping me :)

I think the issue was the lack of a handler, my bad, im burnout
