### ISSUE TITLE
Doesn't work when using router.param

### ISSUE THREAD

**Issue by tejashah88** [davidbanham/express-async-errors#8]
Consider this code:

```javascript
const express = require('express')
require('express-async-errors')
const app = express()

app.get('/test', async (req, res) => {
  throw Error('custom message')
})

app.param('param', async function(req, res, next, param) {
  throw Error('custom message with param ' + param);
})

app.get('/test/:param', async (req, res, next) => {
  throw Error('custom message')
})

app.use((err, req, res, next) => {
  console.log('Catch error:', err.message)
  res.status(418)
  res.send('Error handled!')
});

app.listen(3000, () => console.log('Server started on 3000!'))

process.on('unhandledRejection', reason => {
  console.error('unhandledRejection:', reason)
})
```

This is using the latest version of express, which is currently v4.16.2

Calling `localhost:3000/test` will have the error caught within express, but calling `localhost:3000/test/example` or any other ending parameter results in an uncaught exception. However, calling `next(error)` obviously still works. I don't mind doing that but I'd prefer not having inconsistencies between which express functions have full async support. Thanks!

**Comment by davidbanham** [comment]
Thanks for the issue. That's definitely annoying behaviour. Not something I've run across as I just don't tend to use the `param` API personally.

I'd definitely like to see this fixed, but I'm not sure when I'll have a chance to look at it as I've got a bit on my plate at the moment. So I'll close this out when I get to it, but PRs very welcome if somebody else wants to take a run at this.
