### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by wilsonjackson** [davidbanham/express-async-errors#9]
Hey, just wondering if you could cut a new npm release to get this change out:

https://github.com/davidbanham/express-async-errors/commit/36c530a5f097c20e75de0b245dae727b972d67bd#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L28

From the commit message I gather it was for the travis build, but it also impacted me in a real project. The tl;dr version: when using `dependencies`, express-async-errors ends up with its own, nested express, which is what it patches — so the express in my project's package.json is unaffected. This problem is solved by the change to `peerDependencies`. (I actually cloned this lib to make that change and PR it back to you, only to discover it had already been done!)

**Comment by davidbanham** [comment]
Thanks for the issue. What's weird is that I _did_ cut a new release. It's tagged in github and npm knows about it, but wasn't serving it as latest for some reason. It might have been flagged as a pre-release or something.

Anyway, I've cut a new version under `2.1.2` and published it. NPM is definitely serving it now, so you should be G2G.
